# Generated by Django 3.2.7 on 2021-10-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
